import './globals.css';
import { Roboto } from 'next/font/google';
// import { Footer } from './components/Footer';
import { Header } from './components/Header';

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: "400"

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Connect4</title>
      <body className={`${roboto.className}`}>
      <Header />
        {children}
        {/* 
        <Footer /> */}
      </body>
    </html>
  )
}
